// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package users

import (
	"context"

	"zero/user/rpc/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	LoginRes = user.LoginRes
	Response = user.Response

	Users interface {
		Login(ctx context.Context, in *LoginRes, opts ...grpc.CallOption) (*Response, error)
	}

	defaultUsers struct {
		cli zrpc.Client
	}
)

func NewUsers(cli zrpc.Client) Users {
	return &defaultUsers{
		cli: cli,
	}
}

func (m *defaultUsers) Login(ctx context.Context, in *LoginRes, opts ...grpc.CallOption) (*Response, error) {
	client := user.NewUsersClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}
