// Code generated by goctl. DO NOT EDIT.
// Source: video.proto

package server

import (
	"context"

	"zero/video/rpc/internal/logic"
	"zero/video/rpc/internal/svc"
	"zero/video/rpc/video"
)

type VideoServerServer struct {
	svcCtx *svc.ServiceContext
	video.UnimplementedVideoServerServer
}

func NewVideoServerServer(svcCtx *svc.ServiceContext) *VideoServerServer {
	return &VideoServerServer{
		svcCtx: svcCtx,
	}
}

func (s *VideoServerServer) Ping(ctx context.Context, in *video.Request) (*video.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
