// Code generated by goctl. DO NOT EDIT.
package types

type Response struct {
	Code int32             `json:"code"`
	Msg  string            `json:"msg"`
	Data map[string]string `json:"data"`
}

type RegisterReq struct {
	Username string `json:"username" form:"username"`
	Password string `json:"password" form:"password"`
	Phone    int64  `json:"phone" form:"phone"`
}

type LoginReq struct {
	Username string `form:"username"`
	Password string `form:"password"`
}
