// Code generated by goctl. DO NOT EDIT.
// Source: video.proto

package videoclient

import (
	"context"

	"zero/video/rpc/video"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = video.Request
	Response = video.Response

	Video interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultVideo struct {
		cli zrpc.Client
	}
)

func NewVideo(cli zrpc.Client) Video {
	return &defaultVideo{
		cli: cli,
	}
}

func (m *defaultVideo) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
