// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"zero/user/rpc/internal/logic"
	"zero/user/rpc/internal/svc"
	"zero/user/rpc/user"
)

type UseSrvServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUseSrvServer
}

func NewUseSrvServer(svcCtx *svc.ServiceContext) *UseSrvServer {
	return &UseSrvServer{
		svcCtx: svcCtx,
	}
}

// 用户登录
func (s *UseSrvServer) Login(ctx context.Context, in *user.LoginRequest) (*user.LoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

// 用户注册
func (s *UseSrvServer) Register(ctx context.Context, in *user.RegisterRequest) (*user.RegisterResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

// 用户信息
func (s *UseSrvServer) UserInfo(ctx context.Context, in *user.UserInfoRequest) (*user.UserInfoResponse, error) {
	l := logic.NewUserInfoLogic(ctx, s.svcCtx)
	return l.UserInfo(in)
}

// 修改用户信息
func (s *UseSrvServer) Update(ctx context.Context, in *user.UpdateReq) (*user.UpdateResp, error) {
	l := logic.NewUpdateLogic(ctx, s.svcCtx)
	return l.Update(in)
}
